import { Permissions, Permission } from "./permissions";

export const Roles = {
  OWNER_ADMIN: "OWNER_ADMIN",
  OPS_MANAGER: "OPS_MANAGER",
  SERVICE_ADVISOR: "SERVICE_ADVISOR",
  INVENTORY_MANAGER: "INVENTORY_MANAGER",
  ACCOUNTANT: "ACCOUNTANT"
} as const;

export type Role = (typeof Roles)[keyof typeof Roles];

export const DefaultRolePermissions: Record<Role, Permission[]> = {
  [Roles.OWNER_ADMIN]: Object.values(Permissions),
  [Roles.OPS_MANAGER]: [
    Permissions.USERS_READ,
    Permissions.USERS_UPDATE,
    Permissions.USERS_DISABLE,
    Permissions.ROLES_READ,
    Permissions.PERMISSIONS_READ,
    Permissions.CUSTOMERS_READ,
    Permissions.CUSTOMERS_CREATE,
    Permissions.CUSTOMERS_UPDATE,
    Permissions.VEHICLES_READ,
    Permissions.VEHICLES_CREATE,
    Permissions.VEHICLES_UPDATE,
    Permissions.WORKORDERS_READ_ALL,
    Permissions.WORKORDERS_CREATE,
    Permissions.WORKORDERS_UPDATE_STATUS,
    Permissions.WORKORDERS_BILLING_EDIT,
    Permissions.WORKORDERS_ASSIGN_EMPLOYEE,
    Permissions.WORKORDERS_ADD_NOTES,
    Permissions.WORKORDERS_ADD_ATTACHMENTS,
    Permissions.WORKORDERS_READ_SCHEDULED_POOL,
    Permissions.TIMELOGS_CREATE_SELF,
    Permissions.TIMELOGS_READ_SELF,
    Permissions.TIMELOGS_READ_ALL,
    Permissions.PARTS_READ,
    Permissions.PARTS_CREATE,
    Permissions.PARTS_UPDATE,
    Permissions.SERVICES_READ,
    Permissions.SERVICES_CREATE,
    Permissions.SERVICES_UPDATE,
    Permissions.SERVICES_PRICE_UPDATE,
    Permissions.INVENTORY_PRICE_UPDATE,
    Permissions.INVENTORY_RECEIVE,
    Permissions.INVENTORY_ADJUST,
    Permissions.INVENTORY_ISSUE_TO_WORKORDER,
    Permissions.INVENTORY_COUNTER_SALE,
    Permissions.INVENTORY_REPORTS_READ,
    Permissions.INVOICES_READ,
    Permissions.INVOICES_CREATE,
    Permissions.INVOICES_CLOSE,
    Permissions.PAYMENTS_CREATE,
    Permissions.PAYMENTS_READ,
    Permissions.PAYABLES_READ,
    Permissions.PAYABLES_UPDATE,
    Permissions.EXPENSES_READ,
    Permissions.EXPENSES_CREATE,
    Permissions.EXPENSES_UPDATE,
    Permissions.EXPENSES_DELETE,
    Permissions.REPORTS_READ_SALES,
    Permissions.REPORTS_READ_PROFIT,
    Permissions.REPORTS_READ_INVENTORY,
    Permissions.REPORTS_EXPORT_PDF,
    Permissions.AUDITLOGS_READ
  ],
  [Roles.SERVICE_ADVISOR]: [
    Permissions.CUSTOMERS_READ,
    Permissions.CUSTOMERS_CREATE,
    Permissions.CUSTOMERS_UPDATE,
    Permissions.VEHICLES_READ,
    Permissions.VEHICLES_CREATE,
    Permissions.VEHICLES_UPDATE,
    Permissions.WORKORDERS_READ_ALL,
    Permissions.WORKORDERS_READ_SCHEDULED_POOL,
    Permissions.WORKORDERS_CREATE,
    Permissions.WORKORDERS_UPDATE_STATUS,
    Permissions.WORKORDERS_BILLING_EDIT,
    Permissions.WORKORDERS_ASSIGN_EMPLOYEE,
    Permissions.WORKORDERS_ADD_NOTES,
    Permissions.WORKORDERS_ADD_ATTACHMENTS,
    Permissions.TIMELOGS_CREATE_SELF,
    Permissions.TIMELOGS_READ_SELF,
    Permissions.PARTS_READ,
    Permissions.SERVICES_READ,
    Permissions.INVENTORY_ISSUE_TO_WORKORDER,
    Permissions.INVENTORY_COUNTER_SALE,
    Permissions.INVOICES_READ,
    Permissions.INVOICES_CREATE,
    Permissions.INVOICES_CLOSE,
    Permissions.PAYMENTS_CREATE,
    Permissions.PAYMENTS_READ,
    Permissions.REPORTS_READ_SALES
  ],
  [Roles.INVENTORY_MANAGER]: [
    Permissions.PARTS_READ,
    Permissions.PARTS_CREATE,
    Permissions.PARTS_UPDATE,
    Permissions.SERVICES_READ,
    Permissions.INVENTORY_RECEIVE,
    Permissions.INVENTORY_ADJUST,
    Permissions.INVENTORY_ISSUE_TO_WORKORDER,
    Permissions.INVENTORY_COUNTER_SALE,
    Permissions.INVENTORY_PRICE_UPDATE,
    Permissions.INVENTORY_REPORTS_READ,
    Permissions.INVOICES_READ,
    Permissions.PAYABLES_READ,
    Permissions.PAYABLES_UPDATE
  ],
  [Roles.ACCOUNTANT]: [
    Permissions.CUSTOMERS_READ,
    Permissions.VEHICLES_READ,
    Permissions.WORKORDERS_READ_ALL,
    Permissions.PARTS_READ,
    Permissions.SERVICES_READ,
    Permissions.INVENTORY_REPORTS_READ,
    Permissions.INVOICES_READ,
    Permissions.PAYMENTS_READ,
    Permissions.EXPENSES_READ,
    Permissions.PAYABLES_READ,
    Permissions.REPORTS_READ_SALES,
    Permissions.REPORTS_READ_PROFIT,
    Permissions.REPORTS_READ_INVENTORY,
    Permissions.REPORTS_EXPORT_PDF,
    Permissions.AUDITLOGS_READ
  ]
};
